name: "Podcast Generator"
author: "John MWadime"
decription: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
bradning:
  icon: "git-branch"
  color: "blue"
inputs: 
  email:
    description: The Commiter's Email Address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The Committer's name
    required: true
    default: ${{github.actor}}